name: test
on: [push, pull_request]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Install dependencies
        run: |
          bundle config set path vendor/bundle
          bundle config set without development
          bundle install --jobs 4 --retry 3
      - name: Run tests
        run: bundle exec rake
